---
# Arrs: https://wiki.servarr.com/
version: "3"
services:

  # https://github.com/linuxserver/docker-radarr
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    # container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /docker/docker-compose/privateer/config/radarr:/config
      - /mnt/mobius/Video/Movies:/movies
      - /mnt/mobius/staging/qbittorrent:/downloads
    restart: unless-stopped
    ports: 
      - 7878:7878
      
  # https://github.com/linuxserver/docker-sonarr
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    # container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /docker/docker-compose/privateer/config/sonarr:/config
      - /mnt/mobius/Video/TV-shows:/tv
      - /mnt/mobius/staging/qbittorrent:/downloads
    restart: unless-stopped
    ports: 
      - 8989:8989

  # https://github.com/linuxserver/docker-lidarr
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    # container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /docker/docker-compose/privateer/config/lidarr:/config
      - /mnt/mobius/Music/library:/music
      - /mnt/mobius/staging/qbittorrent:/downloads
    restart: unless-stopped
    ports: 
      - 8686:8686

  # https://github.com/linuxserver/docker-prowlarr
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    # container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /docker/docker-compose/privateer/config/prowlarr:/config
    restart: unless-stopped
    ports: 
      - 9696:9696

  # https://github.com/linuxserver/docker-bazarr
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    # container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /docker/docker-compose/privateer/config/bazarr:/config
      - /mnt/mobius/Video/Movies:/movies
      - /mnt/mobius/Video/TV-shows:/tv
    restart: unless-stopped
    ports: 
      - 6767:6767

  # watchtower
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=America/New_York
      - WATCHTOWER_CLEANUP=true