---
# Arrs: https://wiki.servarr.com/
version: "3"
services:

  # https://github.com/linuxserver/docker-radarr
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    hostname: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /docker/docker-compose/privateer/config/radarr:/config
      - /mnt/mobius/Video/Movies:/movies
      - /mnt/mobius/staging/qbittorrent:/downloads
      - /mnt/mobius/staging/qbittorrent:/mnt/mobius/staging/qbittorrent
    restart: unless-stopped
    ports: 
      - 7878:7878
      
  # https://github.com/linuxserver/docker-sonarr
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    hostname: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /docker/docker-compose/privateer/config/sonarr:/config
      - /mnt/mobius/Video/TV-shows:/tv
      - /mnt/mobius/staging/qbittorrent:/downloads
      - /mnt/mobius/staging/qbittorrent:/mnt/mobius/staging/qbittorrent
    restart: unless-stopped
    ports: 
      - 8989:8989

  # https://github.com/linuxserver/docker-lidarr
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    hostname: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /docker/docker-compose/privateer/config/lidarr:/config
      - /mnt/mobius/Music/library:/music
      - /mnt/mobius/staging/qbittorrent:/downloads
      - /mnt/mobius/staging/qbittorrent:/mnt/mobius/staging/qbittorrent
    restart: unless-stopped
    ports: 
      - 8686:8686

  # https://github.com/linuxserver/docker-prowlarr
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    hostname: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /docker/docker-compose/privateer/config/prowlarr:/config
    restart: unless-stopped
    ports: 
      - 9696:9696

  # https://github.com/linuxserver/docker-bazarr
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    hostname: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /docker/docker-compose/privateer/config/bazarr:/config
      - /mnt/mobius/Video/Movies:/movies
      - /mnt/mobius/Video/TV-shows:/tv
    restart: unless-stopped
    ports: 
      - 6767:6767

  # https://github.com/FlareSolverr/FlareSolverr#installation
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    hostname: flaresolverr
    environment:
      - LOG_LEVEL=info
    restart: unless-stopped
    ports: 
      - 8191:8191

  # Plex Meta Manager
  plex-meta-manager:
    image: meisnate12/plex-meta-manager
    container_name: plex-meta-manager
    environment:
      - TZ=America/New_York #optional
    volumes:
      - /docker/docker-compose/privateer/config/pmm:/config
    restart: unless-stopped
